apiVersion: apps/v1
kind: Deployment
metadata:
  name: academy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academy-service
  template:
    metadata:
      labels:
        app: academy-service
    spec:
      containers:
      - name: academy-service
        image: <your-docker-image-path>/academy-service:latest
        ports:
        - containerPort: 5001
        env:
        - name: API_BASE_URL
          value: "http://nats-streaming:4222"
        - name: NATS_URL
          value: "nats://nats-streaming:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: academy-service
spec:
  type: NodePort
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30008
  selector:
    app: academy-service
