apiVersion: apps/v1
kind: Deployment
metadata:
  name: academy-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academy-service
  template:
    metadata:
      labels:
        app: academy-service
    spec:
      containers:
        - name: academy-service
          image: academy-service:latest # Replace with your image
          env:
            - name: NATS_URL
              value: "nats://nats-streaming:4222"
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: academy-service
spec:
  selector:
    app: academy-service
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
