apiVersion: apps/v1
kind: Deployment
metadata:
  name: academy-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academy-ui
  template:
    metadata:
      labels:
        app: academy-ui
    spec:
      containers:
        - name: academy-ui
          image: academy-ui:latest # Replace with your image
          env:
            - name: API_BASE_URL
              value: "http://academy-service:5001"
            - name: API_COMMONSERVICE_URL
              value: "http://common-service:3004"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: academy-ui
spec:
  selector:
    app: academy-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
