apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-ui
  template:
    metadata:
      labels:
        app: admin-ui
    spec:
      containers:
        - name: admin-ui
          image: admin-ui:latest # Replace with your image
          env:
            - name: API_BASE_URL
              value: "http://auth-service:5000"
            - name: UI_ACADEMY_URL
              value: "http://admin-academy-ui:4201"
          ports:
            - containerPort: 4200
---
apiVersion: v1
kind: Service
metadata:
  name: admin-ui
spec:
  selector:
    app: admin-ui
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
  type: ClusterIP
