apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-ui
  template:
    metadata:
      labels:
        app: admin-ui
    spec:
      containers:
      - name: admin-ui
        image: <your-docker-image-path>:latest
        ports:
        - containerPort: 4200
        env:
        - name: API_BASE_URL
          value: "http://auth-service:5000"
        - name: UI_ACADEMY_URL
          value: "http://admin-academy-ui:4201"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-ui
spec:
  type: NodePort
  ports:
  - port: 4200
    targetPort: 4200
    nodePort: 30003
  selector:
    app: admin-ui
