apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: <your-docker-image-path>/auth-service:latest
        ports:
        - containerPort: 5000
        env:
        - name: API_BASE_URL
          value: "http://nats-streaming:4222"
        - name: NATS_URL
          value: "nats://nats-streaming:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30004
  selector:
    app: auth-service
