apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-service
  template:
    metadata:
      labels:
        app: common-service
    spec:
      containers:
      - name: common-service
        image: <your-docker-image-path>/common-service:latest
        ports:
        - containerPort: 3004
---
apiVersion: v1
kind: Service
metadata:
  name: common-service
spec:
  type: NodePort
  ports:
  - port: 3004
    targetPort: 3004
    nodePort: 30007
  selector:
    app: common-service
