apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: common-service
  template:
    metadata:
      labels:
        app: common-service
    spec:
      containers:
        - name: common-service
          image: common-service:latest # Replace with your image
          ports:
            - containerPort: 3004
---
apiVersion: v1
kind: Service
metadata:
  name: common-service
spec:
  selector:
    app: common-service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
  type: ClusterIP
