apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: veryown.com  # Replace with your domain or remove if not using host-based routing
      http:
        paths:
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: landing-page-cluster-ip-service
                port:
                  number: 3002

    # Route for the SSO subdomain
    - host: sso.veryown.com  # Replace with your SSO subdomain
      http:
        paths:
          - path: /?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: sso-ui-cluster-ip-service
                port:
                  number: 3001  # Replace with the SSO service port




# kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.11.2/deploy/static/provider/cloud/deploy.yaml