apiVersion: apps/v1
kind: Deployment
metadata:
  name: sso-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sso-ui
  template:
    metadata:
      labels:
        app: sso-ui
    spec:
      containers:
      - name: sso-ui
        image: <your-docker-image-path>:latest
        ports:
        - containerPort: 3001
        env:
        - name: API_BASE_URL
          value: "http://auth-service:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: sso-ui
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30001
  selector:
    app: sso-ui
