apiVersion: apps/v1
kind: Deployment
metadata:
  name: sso-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sso-ui
  template:
    metadata:
      labels:
        app: sso-ui
    spec:
      containers:
        - name: sso-ui
          image: sso-ui:latest # Replace with your image
          env:
            - name: API_BASE_URL
              value: "http://auth-service:5000"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sso-ui
spec:
  selector:
    app: sso-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
