# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port your app runs on
EXPOSE 3004

# Define the command to run your app using CMD
CMD ["npm", "start"]


# Docker build : docker build -f dockerfile.dev -t adhirajk/common-service:1.0.0 .

# docker run -p 3004:3004 adhirajk/common-service:1.0.0

# recheck if this is optimal for tagging and pushing

# docker tag adhirajk/common-service:1.0.0 adhirajk/common-service:1.0.0

# docker push adhirajk/common-service:1.0.0