apiVersion: apps/v1
kind: Deployment
metadata:
  name: academy-service-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academy-service
  template:
    metadata:
      labels:
        app: academy-service
    spec:
      containers:
        - name: academy-service
          image: docker.io/adhirajk/academy-service:1.0.5
          ports:
            - containerPort: 5001
          env:
            - name: NATS_URL
              value: https://nats-streaming-cluster-ip-service:4222
---
apiVersion: v1
kind: Service
metadata:
  name: academy-service-cluster-ip-service
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: academy-service
  ports:
    - port: 5001
      targetPort: 5001
