apiVersion: apps/v1
kind: Deployment
metadata:
  name: academy-ui-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: academy-ui
  template:
    metadata:
      labels:
        app: academy-ui
    spec:
      containers:
        - name: academy-ui
          image: docker.io/adhirajk/academy-ui:1.0.9
          ports:
            - containerPort: 80  # Internal port exposed by the container
          env:
            - name: API_BASE_URL
              value: https://academy-service:5001  # Service name for academy_service
            - name: API_COMMONSERVICE_URL
              value: https://common-service:3004  # Service name for common_service
---
apiVersion: v1
kind: Service
metadata:
  name: academy-ui-cluster-ip-service
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: academy-ui
  ports:
    - port: 3000  # Exposed port
      targetPort: 80  # The port inside the container
