apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: docker.io/adhirajk/admin-service:1.0.2
          ports:
            - containerPort: 3003
          env:
            - name: NATS_URL
              value: https://nats-streaming-cluster-ip-service:4222
---
apiVersion: v1
kind: Service
metadata:
  name: admin-service-cluster-ip-service
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: admin-service
  ports:
    - port: 3003
      targetPort: 3003
