apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: docker.io/adhirajk/auth-service:1.1.1 
          ports:
            - containerPort: 5000
          env:
            - name: NATS_URL
              value: https://nats-streaming-cluster-ip-service:4222
---                  
apiVersion: v1
kind: Service
metadata:
  name: auth-service-cluster-ip-service
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 5000
      targetPort: 5000
