apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: veryown-in-tls
spec:
  secretName: veryown-in  # Specifies where the certificate must be stored after it is obtained by the cert manager
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: veryown.in
  dnsNames:
    - veryown.in
    - '*.veryown.in'


 # https://ruanbekker.hashnode.dev/cert-manager-dns-challenge-with-cloudflare-on-kubernetes