apiVersion: apps/v1
kind: Deployment
metadata:
  name: sso-ui-deployment
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sso-ui
  template:
    metadata:
      labels:
        app: sso-ui
    spec:
      containers:
        - name: sso-ui
          image: docker.io/adhirajk/sso_ui:1.0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: API_BASE_URL
              value: https://auth-service  # Service name for auth_service nats://nats-streaming-cluster-ip-service:4222
---
apiVersion: v1
kind: Service
metadata:
  name: sso-ui-cluster-ip-service
  namespace: backend
spec:
  type: ClusterIP
  selector:
    app: sso-ui
  ports:
    - port: 3001
      targetPort: 80
