apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: auth_service_image  # Replace with your image
          ports:
            - containerPort: 5000
          env:
            - name: NATS_URL
              value: nats://nats-streaming:4222
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - port: 5000
      targetPort: 5000
