# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install project dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Expose the port that the Angular app will run on
EXPOSE 4201

# Start the Angular development server
CMD ["npm", "start"]

# docker build -f dockerfile.dev -t adhirajk/admin_academy_ui .

# docker run -p 4201:4201 -v /app/node_modules -v ${PWD}:/app adhirajk/admin_academy_ui