# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port your app runs on
EXPOSE 5000

# Define the command to run your app using CMD
CMD ["npm", "start"]


# Docker build : docker build -f dockerfile.dev -t adhirajk/auth-service:1.1.2 .

# docker run -p 5000:5000 adhirajk/auth-service:1.1.2

# recheck if this is optimal for tagging and pushing

# docker tag adhirajk/auth-service:1.1.2 adhirajk/auth-service:1.1.2

# docker push adhirajk/auth-service:1.1.2
