# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the container
COPY . .

# Expose the port your app runs on
EXPOSE 5001

# Define the command to run your app using CMD
CMD ["npm", "start"]


# Docker build : docker build -f dockerfile.dev -t adhirajk/academy-service:1.0.6 .

# docker run -p 5000:5000 adhirajk/academy-service:1.0.6

# recheck if this is optimal for tagging and pushing

# docker tag adhirajk/academy-service:1.0.6 adhirajk/academy-service:1.0.6

# docker push adhirajk/academy-service:1.0.6

